# Generated by Django 5.0.1 on 2024-01-31 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_phone_no_account_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_more_info',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
