# Generated by Django 5.0.1 on 2024-02-02 17:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_event_eventdetails_eventpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpicture',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Images'),
        ),
    ]
