# Generated by Django 5.0.1 on 2024-02-02 18:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_eventpicture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='event_poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Event Posters'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Event Posters'),
        ),
    ]
